// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvpwSDswNFK400uWxyHt7i4FEUU7_tolw',
    appId: '1:134466084022:web:091b6520426e74a1759a17',
    messagingSenderId: '134466084022',
    projectId: 'docscanner-f8ab9',
    authDomain: 'docscanner-f8ab9.firebaseapp.com',
    storageBucket: 'docscanner-f8ab9.appspot.com',
    measurementId: 'G-KEQPED5NW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdeh-OY9QFZNQYDO_AgL5mKljutEhtWio',
    appId: '1:134466084022:android:63f06e2d89a9a46f759a17',
    messagingSenderId: '134466084022',
    projectId: 'docscanner-f8ab9',
    storageBucket: 'docscanner-f8ab9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQAGi4JcjvYPQHwytO8raWKOq_eH5cadk',
    appId: '1:134466084022:ios:1ea89aa7aeb455be759a17',
    messagingSenderId: '134466084022',
    projectId: 'docscanner-f8ab9',
    storageBucket: 'docscanner-f8ab9.appspot.com',
    iosClientId: '134466084022-3qfjrbrb83kqcgtd9qml5vdndd9p8k1f.apps.googleusercontent.com',
    iosBundleId: 'com.example.docscanner',
  );
}
